import { PropertyHomes } from '@/app/types/properyHomes';

export const propertyHomes: PropertyHomes[] = [
  {
    name: 'Квартира 111 м²',
    slug: 'capital-111',
    category: 'capital',
    location: 'ЖК «ALIA», Москва',
    rate: '3 000 000 ₽',
    beds: 3,
    baths: 2,
    area: 111,
    images: [
      { src: '/images/property/property-1/property-cover-1.jpg' },
      { src: '/images/property/property-1/property-1.jpg' },
      { src: '/images/property/property-1/property-2.jpg' },
      { src: '/images/property/property-1/property-3.jpg' },
    ],
    description: [
      'Проект ремонта квартиры площадью 111 м² в современном стиле. Выполнили полный цикл работ — от замеров до чистовой отделки и установки сантехники. Смета фиксируется до старта, сроки — по договору.',
      'В рамках работ выполнены демонтаж отделки от застройщика (WhiteBox), выравнивание стен и пола, разводка электрики и сантехники, установка освещения, укладка напольных покрытий и монтаж дверей, покраска стен. Отдельное внимание — шумоизоляции и эргономике.',
      'Кухня-гостиная зонирована лёгкими перегородками, предусмотрены скрытые системы хранения и тёплый пол в мокрых зонах.',
      'Финальная комплектация включает подбор материалов, контроль поставок и авторский надзор.',
    ],
    features: [
      {
        title: 'Состав работ',
        description: 'Демонтаж отделки (WhiteBox), штукатурка под маяк, разводка инженерии Rehau, малярные работы, укладка паркета.',
        icon: 'solar:settings-linear',
        image: '/images/SVGs/property-details.svg',
      },
      {
        title: 'Инженерия и безопасность',
        description: 'Умное освещение, датчики протечки, система вентиляции с фильтрацией воздуха, мастер-выключатель.',
        icon: 'solar:shield-check-linear',
        image: '/images/SVGs/property-details.svg',
      },
      {
        title: 'Качество и гарантия',
        description: 'Тройной контроль качества: прораб, технадзор и автор проекта. Гарантия на все работы — 3 года.',
        icon: 'solar:medal-star-linear',
        image: '/images/SVGs/property-details.svg',
      },
    ],
    workItems: [
      { title: 'Покраска стен', icon: 'ph:paint-brush-household' },
      { title: 'Укладка паркета', icon: 'ph:ruler' },
      { title: 'Электрика', icon: 'ph:lightning' },
      { title: 'Сантехника', icon: 'ph:drop' },
      { title: 'Умный дом', icon: 'ph:cpu' },
    ],
  },
  {
    name: 'Квартира 78 м²',
    slug: 'capital-78',
    category: 'capital',
    location: 'ЖК «FULL HOUSE», Москва',
    rate: 'от 980 000 ₽',
    beds: 3,
    baths: 2,
    area: 78,
    images: [
      { src: '/images/property/property-2/property-cover-2.jpg' },
      { src: '/images/property/property-2/property-1.jpg' },
      { src: '/images/property/property-2/property-2.jpg' },
      { src: '/images/property/property-2/property-3.jpg' },
    ],
    description: [
      'Капитальный ремонт в ЖК «FULL HOUSE». Мы превратили бетонную коробку в уютное современное пространство.',
      'Были заменены все инженерные коммуникации, выполнена перепланировка для увеличения полезной площади кухни.',
      'В отделке использованы премиальные материалы: керамогранит, инженерная доска и декоративная штукатурка.',
    ],
    features: [
      {
        title: 'Перепланировка',
        description: 'Объединение кухни и гостиной, создание мастер-спальни с гардеробом и собственным санузлом.',
        icon: 'solar:ruler-pen-linear',
        image: '/images/SVGs/property-details.svg',
      },
      {
        title: 'Премиальная отделка',
        description: 'Итальянский керамогранит, шпонированные стеновые панели, скрытый плинтус и двери-невидимки.',
        icon: 'solar:palet-linear',
        image: '/images/SVGs/property-details.svg',
      },
    ],
    workItems: [
      { title: 'Перепланировка', icon: 'ph:wall' },
      { title: 'Теплый пол', icon: 'ph:thermometer-hot' },
      { title: 'Кондиционирование', icon: 'ph:wind' },
      { title: 'Шумоизоляция', icon: 'ph:speaker-slash' },
    ],
  },
  {
    name: 'Квартира 110 м²',
    slug: 'designer-110',
    category: 'designer',
    location: 'ЖК «Кутузовград», Москва',
    rate: '3 250 000 ₽',
    beds: 3,
    baths: 2,
    area: 110,
    images: [
      { src: '/images/property/property-3/property-cover-3.jpg' },
      { src: '/images/property/property-3/property-1.jpg' },
      { src: '/images/property/property-3/property-2.jpg' },
      { src: '/images/property/property-3/property-3.jpg' },
    ],
    description: [
      'Дизайнерский ремонт квартиры в ЖК «Кутузовград», с авторским надзором и подбором всех чистовых материалов.',
      'Фокус проекта — точная реализация визуальной концепции, выверенная электрика и встроенные системы хранения.',
    ],
  },
  {
    name: 'Квартира 104 м²',
    slug: 'capital-104',
    category: 'capital',
    location: 'ЖК «Alia», Москва',
    rate: '3 000 000 ₽',
    beds: 2,
    baths: 2,
    area: 104,
    images: [
      { src: '/images/property/property-4/property-cover-4.jpg' },
      { src: '/images/property/property-4/property-1.jpg' },
      { src: '/images/property/property-4/property-2.jpg' },
      { src: '/images/property/property-4/property-3.jpg' },
    ],
    description: [
      'Косметический ремонт компактной квартиры с обновлением отделки, освещения и сантехнических зон.',
      'Проект ориентирован на быстрый запуск работ и прогнозируемый бюджет без переплат.',
    ],
  },
  {
    name: 'Квартира 36 м²',
    slug: 'capital-36',
    category: 'capital',
    location: 'ЖК «ALIA», Москва',
    rate: '1 380 000 ₽',
    beds: 1,
    baths: 1,
    area: 36,
    images: [
      { src: '/images/property/property-5/property-cover-5.jpg' },
      { src: '/images/property/property-5/property-1.jpg' },
      { src: '/images/property/property-5/property-2.jpg' },
      { src: '/images/property/property-5/property-3.jpg' },
    ],
    description: [
      'Капитальный ремонт семейной квартиры с полной заменой инженерии, выравниванием поверхностей и новой отделкой.',
    ],
  },
  {
    name: 'Коммерческий ремонт 87,5 м²',
    slug: 'commercial-87.5',
    category: 'commercial',
    location: 'ЖК «Событие», Москва',
    rate: '3 500 000 ₽',
    beds: 2,
    baths: 2,
    area: 87.5,
    images: [
      { src: '/images/property/property-6/property-cover-6.jpg' },
      { src: '/images/property/property-6/property-1.jpg' },
      { src: '/images/property/property-6/property-2.jpg' },
      { src: '/images/property/property-6/property-3.jpg' },
    ],
    description: [
      'Коммерческий ремонт офиса с подготовкой инженерных сетей, перегородок и зон общего пользования.',
    ],
  },
  {
    name: 'Косметический ремонт 48 м²',
    slug: 'capital-48',
    category: 'capital',
    location: 'ЖК «Берег», Новосибирск',
    rate: 'от 360 000 ₽',
    beds: 2,
    baths: 1,
    area: 48,
    images: [
      { src: '/images/property/property-9/property-cover-9.jpg' },
      { src: '/images/property/property-9/property-1.jpg' },
      { src: '/images/property/property-9/property-2.jpg' },
      { src: '/images/property/property-9/property-3.jpg' },
    ],
    description: [
      'Косметический ремонт квартиры 48 м² с обновлением стен, полов, электрики и сантехники.',
    ],
  },
];

export function getPropertyBySlug(slug: string) {
  return propertyHomes.find((item) => item.slug === slug) ?? null;
}
